import localFont from "next/font/local"
import "./globals.css"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-[#032541] text-[#032541] dark:text-white`}
      >
   <main className="my-4">
     <Navbar />
     <div >
      {children}
     </div>
      
       <Footer />
   </main>
      </body>
    </html>
  )
}
